[package]
name = "readability"
version = "0.1.2"
authors = ["Hiroki Kumamoto <kumabook@live.jp>"]
license = "MIT"
homepage = "https://github.com/kumabook/readability"
repository = "https://github.com/kumabook/readability.git"
description = "Port of arc90's readability project to rust"
keywords = ["readability"]
categories = []


[dependencies]
regex            = "^0.2"
url              = "^1.5"
html5ever        = "^0.18.0"
hyper            = "0.10.12"
hyper-native-tls = "0.2.4"
lazy_static      = "^0.2"
